name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - release
      - develop
      - 'feature/**'
      - 'bugfix/**'
      - 'hotfix/**'
      - 'fix/**'
  pull_request:
    branches:
      - main
      - release
      - develop
permissions:
  checks: write
  contents: write


jobs:
  prepare:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Prepare
        run: echo "Prepare step"


  lint:
    runs-on: ubuntu-latest
    needs: prepare
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.18.0'
      - name: Install dependencies
        run: npm install
        working-directory: ./my-project
      - name: Run ESLint
        run: npx eslint . --format json --output-file eslint-report.json
        working-directory: ./my-project
      - name: Upload ESLint Report
        uses: actions/upload-artifact@v3
        with:
          name: eslint-report
          path: ./my-project/eslint-report.json

  tests:
  runs-on: ubuntu-latest
  needs: lint
  steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20.18.0'
    - name: Install dependencies
      run: npm install
      working-directory: ./my-project
    - name: Run tests
      run: npm run test
      working-directory: ./my-project


  build:
    runs-on: ubuntu-latest
    needs: tests
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Build
        run: echo "Build step"

  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/release'
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Deploy
        run: echo "Deploy step"

  notify:
    runs-on: ubuntu-latest
    needs: deploy
    if: always()
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Notify
        run: echo "Notify step"
